config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount ActionCable.server => '/cable'
  devise_for :users

  resources :conversations, only: %i[index show new create destroy]
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  # TODO: create logic for paranoid
  acts_as_paranoid
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :user
  has_many :messages, dependent: :destroy
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :conversation

  after_create_commit { MessageBroadcastJob.perform_later(self) }

  def send_at
    created_at.strftime('%H:%M:%S')
  end
end

app/models/user.rb
class User < ApplicationRecord
  # acts_as_paranoid
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :conversations, dependent: :destroy
  has_many :messages, dependent: :destroy

  def name
    email.split('@').first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :set_conversation, only: %i[show destroy]

  def index
    @conversations = Conversation.all
  end

  def show
    @message = Message.new
  end

  def new
    @conversation = Conversation.new
  end

  def create
    @conversation = current_user.conversations.build(conversation_params)
    if @conversation.save
      # TODO: show notification
      flash[:success] = 'Conversation added!'
      redirect_to conversations_path
    else
      render 'new'
    end
  end

  def destroy
    # TODO: add link to destroy conversation
    # TODO: add policy to manage rights
    @conversation.destroy
    redirect_to conversations_path
  end

  private

  def set_conversation
    @conversation = Conversation.find(params[:id])
  end

  def conversation_params
    params.require(:conversation).permit(:topic)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!
  def index; end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/conversations/_conversation.html.slim
li
  = link_to "Enter #{conversation.topic}", conversation_path(conversation)

app/views/conversations/index.html.slim
.section
  .container
    h1.title Conversations
    = link_to 'New conversation', new_conversation_path, class: 'button'
.section
  .container
    ul
      = render @conversations

app/views/conversations/new.html.slim
.section
  .container
    h1.title.has-text-centered Add conversations
.section
  .container
    = form_for @conversation do |f|
      .field.is-horizontal
        .field-label.is-normal
          = f.label :topic, class: 'label'
        .field-body
          .field.has-addons
            .control
              = f.text_field :topic, class: 'input is-primary'
            .control
              = f.submit 'Add', class: 'button is-primary'

app/views/conversations/show.html.slim
.section
  .container
    h1.title = @conversation.topic
.section
  .container
    .columns
      .column
        .panel
          .panel-body#messages data-conversation-id= @conversation.id
            = render @conversation.messages
      .column.is-one-third
        .panel
          = form_for @message, url: '#' do |f|
            .field
              .control
                = f.text_area :body, class: 'textarea is-info', placeholder: 'Your message'
            .field
              .control
                = f.submit 'Post', class: 'button is-info'

app/views/home/index.html.slim
.section
  .container
    h1.title Welcome to Chat App
    - if current_user
      p
        | To start chatting choose
        = link_to ' conversation ', conversations_path
        | or create a
        = link_to ' new one', new_conversation_path
    - else
      p
        | To continue
        = link_to ' log in ', new_user_session_path
        | or
        = link_to ' sign up', new_user_registration_path
        |, please

app/views/layouts/_navbar.html.slim
.navbar
  .navbar-brand
    = link_to root_path, class: 'navbar-item' do
      = image_tag 'logo_placeholder.png'
    button.button.navbar-burger
      span
      span
      span
  .navbar-menu
    .navbar-start
      = link_to 'Conversations', conversations_path, class: 'navbar-item'
    .navbar-end
      - if current_user
        = link_to destroy_user_session_path, method: :delete, class: 'navbar-item' do
          = fa_icon('sign-out')
      -else
        = link_to new_user_session_path, class: 'navbar-item' do
          = fa_icon('sign-in')

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Chat
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/bulma/0.6.2/css/bulma.min.css', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    .container
      = render 'layouts/navbar'
    = yield

app/views/messages/_message.html.slim
article.message.is-small
  .message-header
    p = "#{message.user.name} - #{message.send_at}"
  .message-body
    = message.body